### ISSUE TITLE
Single annotation outside Cluster

### ISSUE THREAD

**Issue by Raphzz** [itsbonczek/kingpin#100]
Can you make one single Annotation not merge with the cluster? Remain it single in every zoom aspect.
I dug through the documentation and found nothing related to this.

Thanks!

**Comment by stanislaw** [comment]
This is currently not supported. But why are you including that single annotation to the set of annotations to be clustered? You could keep it separate from your kingpin annotation set and add it to map view manually or you want it to be *sometimes* clustered and sometimes not?
