### ISSUE TITLE
Using with CoreData - Crash whenever app is updated?

### ISSUE THREAD

**Issue by just-a-beginner** [itsbonczek/kingpin#101]
I am using kingpin and love it - thank you for making an amazing Github project. The problem I have is that whenever I release a new version of the app, the app will crash the first time it is run. It works fine when you open it again, but I'd like to fix it. My app is using Core Data but the model is not changing between versions. In researching the issue, people have discussed sometimes having problems with cocoapods and Core Data - something about the resources.sh file... but I don't know enough to try and troubleshoot this bug.

Is this something you have heard of? Is there a fix? Or maybe you can point me int he right direction? I appreciate your help. Yours is the only pod I have installed, which is why I am asking here.

**Comment by stanislaw** [comment]
Hello,

All that sounds really weird as no interference I can imagine that could ever happen between kingpin and Core Data.

We need more details for your report:

- Is it app which is released to AppStore that crashes? Can you somehow reproduce it in your development or staging environment?
- Do you have any crash-reporting tools such Crashlytics i.e. can you obtain some details about crash report?

Shortly: to be able to help you we need thread backtrace for your crash report. Try to find a way to obtain it and we'll work together on your issue.

**Comment by just-a-beginner** [comment]
Hi Stanislaw,

I appreciate your reply - I will get Crashlytics installed and try to replicate the error.

**Comment by stanislaw** [comment]
These links might help you to obtain crash logs without Crashlytics: 

https://developer.apple.com/library/ios/qa/qa1747/_index.html
https://developer.apple.com/library/ios/recipes/xcode_help-devices_organizer/ViewingCrashLogsonaniOSDevice/ViewingCrashLogsonaniOSDevice.html

Also try googling things like: "iOS obtain crash log from device" and you'll see these and other links on topic.

**Comment by just-a-beginner** [comment]
Hi Stanislaw 

In trying to get good logs for this issue, I identified other problems I am having. I am hoping they are related. I will resolve them and post here if it doesn't fix the problem.

I will close the this problem ticket if you'd like me to post again if I need to. I am not sure if I can re-open the issue if I select "close and comment"

Thanks again for your offer of support.

**Comment by stanislaw** [comment]
Nice to hear you made a progress on your issue! Feel free to reopen this ticket if you have any issues.
