### ISSUE TITLE
Support for clustering on specific Annotation types

### ISSUE THREAD

**Issue by joelSimpson** [itsbonczek/kingpin#103]
Hi there!

I've been trying to add some constraints in `KPClusteringController.m` method: `updateVisibleMapAnnotationsOnMapView:(BOOL)animated` to check for a custom bool value in my Annotations because I would like to *not* cluster specific annotations I have on my map.

I have not been successful.
I would like to ask if I'm doing this in the right place or if it would best to try elsewhere.

Thanks!
Joel

**Comment by mjmayank** [comment]
@joelSimpson would it make more sense to just not add those annotations to the array you give the clustering controller in [clusteringController setAnnotations]?

So filter out the annotations you don't want to the clustering controller to touch before you pass them in?

(not 100% sure this works, but this is my understanding from the docs/past usage)

**Comment by stanislaw** [comment]
@joelSimpson sorry for delay in response.

Could you elaborate more on your use case? What @mjmayank wrote makes sense - if you want something not to be clustered - why add it to kingpin's cluster tree at all? I used to ask exactly the same question here: https://github.com/itsbonczek/kingpin/issues/100 but didn't receive answer at that time.

Depending on your use case we could consider adding this functionality but first we need to know what exactly do you need.

**Comment by joelSimpson** [comment]
hi @mjmayank & @stanislaw,

I appreciate the reply and suggestions.  

I've taken a second look at my implementation and, as both of you suggested, by not passing the clustering controller the pins I wish to be ignored should accomplish my desired behaviour.  I will be looking into this in the near future.
