### ISSUE TITLE
Swift 2.0 and bitcode enable

### ISSUE THREAD

**Issue by notiles** [itsbonczek/kingpin#104]
Hello,

I move my project to swift 2.0 on XCode 7.0 and I have to disable bitcode to ensure that my app will compile. 

I get this error with bitcode enable: 

ld: '/Users/xxxxxxx/Documents/WORK/myproject/kingpin-frameworks/iOS/kingpin.framework/kingpin' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

But with bitcode disable I got an other warning when I try to push my app on itunes connect : 

the resulting api analysis file is too large

Thanks for your help

**Comment by stanislaw** [comment]
@notiles, thanks for reporting this. I'll take a look at it asap within 2 days.

**Comment by notiles** [comment]
Perfect, Thanks a lot.

**Comment by stanislaw** [comment]
@notiles could you please try kingpin-frameworks from [enable-bitcode](https://github.com/itsbonczek/kingpin/tree/enable-bitcode) branch? There I have enabled `ENABLE_BITCODE` and rebuilt frameworks with it.

Unfortunately I do not have time to test how submission to iTunesConnect works so I am asking you to do that. Let me know if that works for you.

**Comment by notiles** [comment]
Ok I will try it today! Thanks a lot.

**Comment by notiles** [comment]
@stanislaw I build the app with bitcode enable but now it's an other framework which is not bitcode enabled in my app...

But KingPin look working well with bitcode enable !! 

Thanks a lot.

**Comment by stanislaw** [comment]
Good to know! Thanks for pushing this update live :)
