### ISSUE TITLE
Can't build library

### ISSUE THREAD

**Issue by earl-apps** [itsbonczek/kingpin#110]
Hi!

When I try to clone and build your library I get this BUILD FAILED

<img width="874" alt="snimek obrazovky 2015-10-12 v 16 42 05" src="https://cloud.githubusercontent.com/assets/7859547/10430579/3e678e1e-7100-11e5-9eae-91f1bf2efb97.png">

Thank you for the advice

**Comment by stanislaw** [comment]
To build library this way you have to codesign it. To do that you need a developer certificate.

Be sure to read [Creating iOS/OSX Frameworks: is it necessary to codesign them before distributing to other developers?](http://stackoverflow.com/questions/30963294/creating-ios-osx-frameworks-is-it-necessary-to-codesign-them-before-distributin) for a broader explanation.

P.S. Why are you building kingpin yourself? In case you need framework binaries you have them [here](https://github.com/itsbonczek/kingpin/releases).
