### ISSUE TITLE
declaration of 'MKAnnotation' must be imported from module 'MapKit.MKAnnotation' before it is required

### ISSUE THREAD

**Issue by GabrielCartier** [itsbonczek/kingpin#82]
Not sure if this is related with the update of cocoapods, but I am since having a problem compiling with kingpin in my project. I get an error in kp_2dtree.h

/kp_2dtree.h:14:29: error: declaration of 'MKAnnotation' must be imported from module 'MapKit.MKAnnotation' before it is required

Has anyone ran into that bug too?

**Comment by GabrielCartier** [comment]
adding the ```#import <MapKit/MapKit.h>``` seems to fix the problem, not sure if that is an issue tho. KPGeometry seems to import <MapKit/MKGeometry.h> but that does not import the MKAnnotation protocol.

**Comment by stanislaw** [comment]
Yes, something definitely has changed somewhere as we didn't change anything. But indeed the import of `MapKit/MKAnnotation` was needed in kp_2dtree.h.

I have released new 0.2.4 with this change.

Let me know if it works for you.

**Comment by GabrielCartier** [comment]
Perfect, sorry, should've done the PR, but I wasn't sure if something had changed or not. Tried to backtrack the commits but didn't find anything.

Anyway thanks for the quick PR.
