### ISSUE TITLE
Multiple pins at same location

### ISSUE THREAD

**Issue by chriscdn** [itsbonczek/kingpin#83]
I have an issue with multiple pins at the same location (e.g., different residents in the same apartment building).  The pins stay clustered when you zoom in, which is probably expected behaviour.  Has anyone dealt with this issue, and if so, how?

**Comment by itsbonczek** [comment]
Interesting. You could try disabling clustering when zoomed into a certain level. This would at least show two pins on top of each other rather than one single pin. See @stanislaw's answer here:

https://github.com/itsbonczek/kingpin/issues/76

Hope that helps!
