### ISSUE TITLE
How could I add the count on the annotation?

### ISSUE THREAD

**Issue by nassarofficial** [itsbonczek/kingpin#85]
I want to overlay the count of the cluster on the annotation itself, how is that possible?

**Comment by itsbonczek** [comment]
Check out the ```annotations``` property on KPAnnotation. You should be able to use the count of that set  to accomplish what you want.

https://github.com/itsbonczek/kingpin/blob/master/src/KPAnnotation.h#L28

**Comment by fadion** [comment]
For anyone looking to display the count on annotations, my approach is to set a custom image on the annotationview with a label on top of it. As usually done on the `viewForAnnotation` method, it looks like below (Swift):

```swift
// annotationView is plain MKAnnotationView
annotationView!.image = UIImage(named: "cluster")

let label = UILabel(frame: ...)
// annotation is the MKAnnotation cast to KPAnnotation
label.text = annotation.annotations

annotationView!.addSubview(label)
```

**Comment by itsbonczek** [comment]
Thanks, @fadion!
