### ISSUE TITLE
didSelectAnnotationView not called on single annotation

### ISSUE THREAD

**Issue by fadion** [itsbonczek/kingpin#87]
I really can't tell if this is an issue of kingpin or my own fault, but I'm not getting the `didSelectAnnotationView` to be called on a single annotation. It gets called correctly on clusters.

I'm adjusting both clusters and single annotations (checking with `annotation.isCluster()`) as `MKAnnotationView` in `viewForAnnotation` by adding some custom images and overlaying the cluster number. If there's any chance that code is causing the issue, I can post it here.

What follows is the code I'm currently using. The method isn't called at all on single annotations.

```swift
func mapView(mapView: MKMapView!, didSelectAnnotationView view: MKAnnotationView!) {
    if view.annotation is KPAnnotation {
        let cluster: KPAnnotation = view.annotation as! KPAnnotation
        
        if cluster.annotations.count > 1 {
            let region = MKCoordinateRegionMakeWithDistance(cluster.coordinate, cluster.radius * 2.5, cluster.radius * 2.5)
            
            mapView.setRegion(region, animated: true)
        }
        else if let annotation = cluster.annotations.first as? KPAnnotation {
            println(annotation.title)
        }
    }
}
```

**Comment by itsbonczek** [comment]
Hmm, kingpin doesn't insert itself into MKMapView the delegate chain, so it's likely that something you are doing to configure the single annotation cluster view is causing issues.

Question: Is the callout shown when you select the cluster? If no, you may have done something to block touches from being received by that annotation view. If yes, then we'll have to dig a bit further...

**Comment by fadion** [comment]
That's what I wanted to hear. I was afraid kingpin was preventing the call to `didSelectAnnotationView`, but it's not the case. Did a few tests with a simple MKPinAnnotationView and it works correctly. I'll find out what I'm doing wrong with my custom annotation views.

Thanks.
