### ISSUE TITLE
Annotation pin is changed when long pressed in annotation image and annotation title won't hide

### ISSUE THREAD

**Issue by mathiarasan24** [itsbonczek/kingpin#91]
Hey @itsbonczek @stanislaw @GabrielCartier

Here my problems in kingpin. I have one viewcontroller and it have mkmapview and tableview. We can see only one view at a time mkmapview or tableview. MKMapview and Tableview show and hide based on Height Constraint zero when hide and show based on screen height.

**Problem 1:** When i long press a Annotation image it's change to default annotation pin image. Here my code in  ```- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)``` method ```annotationView.image = [UIImage imageNamed:@"pinone"];```

![annotationpin](https://cloud.githubusercontent.com/assets/11555734/8266723/16a6bfb0-175c-11e5-8c69-f9219d977907.png)

**Problem 2:** I have data that have same lat and long value. So Purple color Annotation label(title: 10 custom Annotations and subtitle: 100 meters [in kingpin]) won't hide. Because no more zoom-in in mapview. It's affect all other annotation which have same data that's too show Annotation label.

I am already tried this too [FAQ: How to disable clustering at a certain zoom level (multiple pins at same location)?](https://github.com/itsbonczek/kingpin/blob/master/Documentation/FAQ.md#how-to-disable-clustering-at-a-certain-zoom-level-multiple-pins-at-same-location). It's doesn't suit this project.
In this project For example: In a Mall have multiple discount coupons for different products. If I have 3 coupons in a mall it's show only one coupon details only. So I need to show as usual annotation label like before said(title: 10 custom Annotations and subtitle: 100 meters [in kingpin]). Because I need to show how many coupons in this mall I don't what show only one coupon. 

![annotiontitle](https://cloud.githubusercontent.com/assets/11555734/8266724/17c279de-175c-11e5-9a5f-b38618cbc68e.png)

```Objective-C
- (void)clusteringController:(KPClusteringController *)clusteringController configureAnnotationForDisplay:(KPAnnotation *)annotation
 {
    if(annotation.annotations.count > 1){
        annotation.title = [NSString stringWithFormat:@"%lu Coupons", (unsigned long)annotation.annotations.count];
        return;
    }
}
- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)annotation {
    
    MKPinAnnotationView *annotationView = nil;
    
    if ([annotation isKindOfClass:[KPAnnotation class]]) {
        
        KPAnnotation *a = (KPAnnotation *)annotation;
        
        if ([annotation isKindOfClass:[MKUserLocation class]]){
            return nil;
        }
     annotationView.canShowCallout = YES;
}
}
```

Hope it will help.. :flushed: :flushed: :flushed:

**Comment by stanislaw** [comment]
@mathiarasan24, thanks for opening separate ticket. In a perfect world you would open two tickets one for each problems because these are different problems but for now one ticket is fine :)

Let's start with problem 1:

I think you're reporting issue similar to #33. Here is the quote from [FAQ](https://github.com/itsbonczek/kingpin/blob/master/Documentation/FAQ.md#how-to-configure-annotations-with-custom-images):

> Note: Notice that it is MKAnnotationView class that should be used for annotations with custom images, not the MKPinAnnotationView which is intended to work specifically with default annotation pin icons provided by Apple. 

Try:

```objective-c
- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)annotation {
    MKAnnotationView *annotationView = nil; // Not MKPinAnnotationView!!
    ...
```

**Comment by mathiarasan24** [comment]
@stanislaw, thanks for answer and that's work's fine too :+1: . This is my first time so i don't know exactly how to do and what to do include xcode also. In future I will follow separate ticket for more than one problem.
Did you understand problem 2: are you find any solution for that :)

**Comment by itsbonczek** [comment]
I'm not sure I completely understand your issue, but is it possible to tweak your data model a bit to better suit kingpin? Perhaps instead of clustering coupon objects, you can cluster the location that the coupon is at? This way, if a place (the mall, for instance) has more than one coupon, the coupons will always be grouped regardless of whether or not clustering is enabled? Let me know if I'm misunderstanding, or if that doesn't make sense.

**Comment by stanislaw** [comment]
@mathiarasan24 , I am pretty sure I don't understand your problem quite well because of description you made is not precise.

Could you please make one more attempt and describe your problem 2 once again?

We are eager to help but first we need to understand your problem :)

Thanks

**Comment by mathiarasan24** [comment]
Hi @stanislaw  @itsbonczek ,
For example: Walmart have multiple products(veg to non veg) each and every products have discount coupons. Take a food product called vegpackedfood. It's have verity of discount coupons based on packing kg size and price. Assume vegpackedfood have minimum 10 discount coupon.
```Objective-C
 - (BOOL)clusteringControllerShouldClusterAnnotations:(KPClusteringController *)clusteringController {
    return self.mapView.zoomLevel < 14; // Find zoom level that suits your dataset
}
```
If i use this method it's show only one discount coupon detail about vegpackedfood. But vegpackedfood have many discount coupons. I need to show all of them. This is not correct way, so I removed and used as usual default code.
Like these many product have minimum 10 discount coupon. If multiple annotation have same discount coupon number, then when I touch a annotation it's show how many coupon(3 Coupons) and then touch another annotation previous annotation title (3 coupons) hide and new annotation pin title will show. But here previous annotation title won't hide.
That's why two annotation title show 3 coupons above map picture shows 3 coupons for two annotation pin. That's the issues. If I zoom out more than 5 annotation show 3 coupons in title. That won't hide.

Hope it's may help to understand. :flushed: :flushed: :flushed:

**Comment by stanislaw** [comment]
@mathiarasan24 , I'm still not getting into your issue.

Let's try something international and interactive: here's my Skype: `stanislaw.pankevich` - feel free to add me and let's talk then.
