### ISSUE TITLE
Show title cluster without tap

### ISSUE THREAD

**Issue by Pades9** [itsbonczek/kingpin#97]
Hi guys,

it is possible show cluster bubble(canShowCallout), without tap? It show me only when I tap on cluster pin. Thank you

**Comment by abiaad** [comment]
That's a MKMapView issue. You need to call selectAnnotation method on your map.
More informations [here](http://stackoverflow.com/a/4181077)

**Comment by itsbonczek** [comment]
Thanks, @abiaad !
